name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/netlify-deploy@master
        with:
          netlify_access_token: ${{secrets.HEROKU_API_KEY}}
          site_name: "akhileshns-demosite"
